### ISSUE TITLE
Hey! There is no issue just a few questions about the project

### ISSUE THREAD

**Issue by k1p1l0** [keboola/developer-portal#95]
Hello!

Thank you for this project, I'm reading it now, it's so useful for me! You're doing great job!

1. I have question about how your serverless.yml and "auth.auth" files work together.

You have this schema in the serverless.yml
```
auth:
    handler: auth.auth
    events:
      -
        http:
          method: post
          path: "auth/login"
      -
        http:
          method: get
          path: "auth/token"
```

You don't use **integration: lambda** with http option.. that's why you have in auth.js file **event.resource** that's give you handle routes with switch (event.resource) {...}

When I've been doing the same in my project it gives me proper I/O but lambda doesn't want to give me response into the API. 

I have only this message
```
{
  "message": "Internal server error"
}
```

Could you tell me why it happens and solve this problem to get proper response into the API GateWay?

**Answer**:
The problem was that I didn't do JSON.stringify(body)..

2) You have "auth.js" file in the "lambda" folder but in serverless.yml you didn't use path "lambda/auth.auth" you just use "auth.auth" skipping "lambda" folder. How?

Thank you!
